version: 2
jobs:
  my_ci_and_cd:
    machine: true
    steps:
    - run: |
        sudo apt update && sudo apt install sshpass -y
    - run: "sshpass -p $can ssh root@13.234.176.102 'ls -ltr' \n"
workflows:
  version: 2
  rolling_update:
    jobs:
    - my_ci_and_cd:
        filters:
          branches:
            only:
            - master
